dist: trusty
language: node_js
node_js:
- '6'

addons:
  sonarqube:
    organization: 'recuencojones-github'
    branches:
      - develop

install:
- npm install

script:
- npm run lint
- npm run doc
- npm run build
- npm test
- sonar-scanner
